on:
  push:
    branches:
      - rohit_branch

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ac78c94a }}

    # install dependencies, build, and test
    - name: npm install, build, and test
      working-directory: test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present


    - uses: azure/appservice-settings@v1
      with:
        app-name: frunchy
        general-settings-json: '{"linuxFxVersion": "NODE|lts"}' #'General configuration settings as Key Value pairs'

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: frunchy
        package: test

    # Azure logout
    - name: logout
      run: |
        az logout
